CST for file: programming_assignment_3-test_file_4.c
Program () [Line: -1]
    Declaration (char) [Line: 5]
        ArrayDeclaration (announcement) [Line: 5]
            ArraySize (2048) [Line: 5]
    Procedure (main) [Line: 8]
        "("
        ParameterType (void) [Line: 8]
        ")"
        "{"
        Declaration (char) [Line: 10]
            ArrayDeclaration (name) [Line: 10]
                ArraySize (100) [Line: 10]
        Assignment (name) [Line: 12]
            Operand ("Robert\x0") [Line: 12]
        Assignment (announcement) [Line: 14]
            Operand ("You've got mail!\x0") [Line: 14]
        FunctionCall (display_announcement) [Line: 15]
        "}"
    Function (empty_string) [Line: 19]
        ReturnType (bool) [Line: 19]
        "("
        ParameterType (char) [Line: 19]
            Parameter (string) [Line: 19]
        ")"
        "{"
        Declaration (int) [Line: 21]
            Variable (i) [Line: 21]
        Declaration (int) [Line: 22]
            Variable (num_bytes_before_null) [Line: 22]
        Declaration (bool) [Line: 23]
            Variable (found_null) [Line: 23]
        Assignment (found_null) [Line: 25]
            Operand (FALSE) [Line: 25]
        Assignment (num_bytes_before_null) [Line: 26]
            Operand (0) [Line: 26]
        Assignment (i) [Line: 27]
            Operand (0) [Line: 27]
        WhileStatement (while) [Line: 28]
            Operator (&&) [Line: 28]
                Operator (<) [Line: 28]
                    Operand (i) [Line: 28]
                    Operand (4096) [Line: 28]
                Operator (!) [Line: 28]
                    Operand (found_null) [Line: 28]
            IfStatement (if) [Line: 30]
                Operator (==) [Line: 30]
                    ArrayAccess (string) [Line: 30]
                        Operand (i) [Line: 30]
                    Operand ('\x0') [Line: 30]
                Assignment (found_null) [Line: 32]
                    Operand (TRUE) [Line: 32]
                ElseStatement (else) [Line: 34]
                    Assignment (num_bytes_before_null) [Line: 36]
                        Operator (+) [Line: 36]
                            Operand (num_bytes_before_null) [Line: 36]
                            Operand (1) [Line: 36]
            Assignment (i) [Line: 38]
                Operator (+) [Line: 38]
                    Operand (i) [Line: 38]
                    Operand (1) [Line: 38]
        Return (return) [Line: 40]
            Operator (==) [Line: 40]
                Operand (num_bytes_before_null) [Line: 40]
                Operand (0) [Line: 40]
        "}"
    Procedure (display_announcement) [Line: 44]
        "("
        ParameterType (char) [Line: 44]
            Parameter (name) [Line: 44]
        ")"
        "{"
        IfStatement (if) [Line: 46]
            Operator (!) [Line: 46]
                FunctionCall (empty_string) [Line: 46]
                    Operand (name) [Line: 46]
            FunctionCall (printf) [Line: 48]
            IfStatement (if) [Line: 49]
                Operator (!) [Line: 49]
                    FunctionCall (empty_string) [Line: 49]
                        Operand (announcement) [Line: 49]
                FunctionCall (printf) [Line: 51]
        "}"
