CST for file: programming_assignment_4-test_file_3.c
Program () [Line: -1]
    Declaration (char) [Line: 5]
        ArrayDeclaration (announcement) [Line: 5]
            ArraySize (2048) [Line: 5]
    Procedure (main) [Line: 8]
        "("
        ParameterType (void) [Line: 8]
        ")"
        "{"
        Declaration (char) [Line: 10]
            ArrayDeclaration (name) [Line: 10]
                ArraySize (100) [Line: 10]
        Assignment (name) [Line: 12]
            Operand ('Robert\x0') [Line: 12]
        Assignment (announcement) [Line: 13]
            Operand ("You've got mail!\x0") [Line: 13]
        FunctionCall (display_announcement) [Line: 14]
        "}"
    Function (empty_string) [Line: 18]
        ReturnType (bool) [Line: 18]
        "("
        ParameterType (char) [Line: 18]
            Parameter (string) [Line: 18]
                ArraySize (4096) [Line: 18]
        ")"
        "{"
        Declaration (int) [Line: 20]
            Variable (i) [Line: 20]
        Declaration (int) [Line: 21]
            Variable (num_bytes_before_null) [Line: 21]
        Declaration (bool) [Line: 22]
            Variable (found_null) [Line: 22]
        Assignment (found_null) [Line: 24]
            Operand (FALSE) [Line: 24]
        Assignment (num_bytes_before_null) [Line: 25]
            Operand (0) [Line: 25]
        Assignment (i) [Line: 26]
            Operand (0) [Line: 26]
        WhileStatement (while) [Line: 27]
            Operator (&&) [Line: 27]
                Operator (<) [Line: 27]
                    Operand (i) [Line: 27]
                    Operand (4096) [Line: 27]
                Operator (!) [Line: 27]
                    Operand (found_null) [Line: 27]
            IfStatement (if) [Line: 29]
                Operator (==) [Line: 29]
                    ArrayAccess (string) [Line: 29]
                        Operand (i) [Line: 29]
                    Operand ('\x0') [Line: 29]
                Assignment (found_null) [Line: 31]
                    Operand (TRUE) [Line: 31]
                ElseStatement (else) [Line: 33]
                    Assignment (num_bytes_before_null) [Line: 35]
                        Operator (+) [Line: 35]
                            Operand (num_bytes_before_null) [Line: 35]
                            Operand (1) [Line: 35]
            Assignment (i) [Line: 37]
                Operator (+) [Line: 37]
                    Operand (i) [Line: 37]
                    Operand (1) [Line: 37]
        Return (return) [Line: 39]
            Operator (==) [Line: 39]
                Operand (num_bytes_before_null) [Line: 39]
                Operand (0) [Line: 39]
        "}"
    Procedure (display_announcement) [Line: 43]
        "("
        ParameterType (char) [Line: 43]
            Parameter (name) [Line: 43]
                ArraySize (512) [Line: 43]
        ")"
        "{"
        IfStatement (if) [Line: 45]
            Operator (!) [Line: 45]
                FunctionCall (empty_string) [Line: 45]
                    Operand (name) [Line: 45]
            FunctionCall (printf) [Line: 47]
            IfStatement (if) [Line: 48]
                Operator (!) [Line: 48]
                    FunctionCall (empty_string) [Line: 48]
                        Operand (announcement) [Line: 48]
                FunctionCall (printf) [Line: 50]
        "}"
