CST for file: programming_assignment_3-test_file_2.c
Program () [Line: -1]
    Procedure (fizzbuzz) [Line: 15]
        "("
        ParameterType (int) [Line: 15]
            Parameter (counter) [Line: 15]
        ")"
        "{"
        Declaration (int) [Line: 17]
            Variable (state) [Line: 17]
        Assignment (state) [Line: 19]
            Operand (0) [Line: 19]
        IfStatement (if) [Line: 20]
            Operator (==) [Line: 20]
                Operator (%) [Line: 20]
                    Operand (counter) [Line: 20]
                    Operand (3) [Line: 20]
                Operand (0) [Line: 20]
            Assignment (state) [Line: 22]
                Operand (1) [Line: 22]
        IfStatement (if) [Line: 24]
            Operator (==) [Line: 24]
                Operator (%) [Line: 24]
                    Operand (counter) [Line: 24]
                    Operand (5) [Line: 24]
                Operand (0) [Line: 24]
            Assignment (state) [Line: 26]
                Operator (*) [Line: 26]
                    Operand (state) [Line: 26]
                    Operator (+) [Line: 26]
                        Operand (2) [Line: 26]
                        Operand (2) [Line: 26]
        IfStatement (if) [Line: 28]
            Operator (==) [Line: 28]
                Operand (state) [Line: 28]
                Operand (1) [Line: 28]
            FunctionCall (printf) [Line: 30]
            ElseStatement (else) [Line: 32]
                IfStatement (if) [Line: 34]
                    Operator (==) [Line: 34]
                        Operand (state) [Line: 34]
                        Operand (2) [Line: 34]
                    FunctionCall (printf) [Line: 36]
                    ElseStatement (else) [Line: 38]
                        IfStatement (if) [Line: 40]
                            Operator (==) [Line: 40]
                                Operand (state) [Line: 40]
                                Operand (4) [Line: 40]
                            FunctionCall (printf) [Line: 42]
                            ElseStatement (else) [Line: 44]
                                FunctionCall (printf) [Line: 46]
        "}"
    Procedure (main) [Line: 56]
        "("
        ParameterType (void) [Line: 56]
        ")"
        "{"
        Declaration (int) [Line: 58]
            Variable (counter) [Line: 58]
        Assignment (counter) [Line: 60]
            Operand (1) [Line: 60]
        WhileStatement (while) [Line: 61]
            Operator (<=) [Line: 61]
                Operand (counter) [Line: 61]
                Operand (100) [Line: 61]
            FunctionCall (fizzbuzz) [Line: 63]
            Assignment (counter) [Line: 64]
                Operator (+) [Line: 64]
                    Operand (counter) [Line: 64]
                    Operand (1) [Line: 64]
            IfStatement (if) [Line: 65]
                Operator (<=) [Line: 65]
                    Operand (counter) [Line: 65]
                    Operand (100) [Line: 65]
                FunctionCall (printf) [Line: 67]
                ElseStatement (else) [Line: 69]
                    FunctionCall (printf) [Line: 71]
        "}"
